import os
import re
import compile_po

# 1. Scan templates for all translatable strings
template_dir = 'templates'
msgids = set()

re_trans = re.compile(r'{%\s*(?:translate|trans)\s+[\'\"](.+?)[\'\"](?:\s+as\s+\w+)?\s*%}')
re_blocktrans = re.compile(r'{%\s*(?:blocktranslate|blocktrans)\s*%}(.+?){%\s*(?:endblocktranslate|endblocktrans)\s*%}', re.DOTALL)
re_filter = re.compile(r'_\([\'\"](.+?)[\'\"]\)')

for root, dirs, files in os.walk(template_dir):
    for f in files:
        if f.endswith('.html'):
            filepath = os.path.join(root, f)
            with open(filepath, 'r', encoding='utf-8') as fh:
                content = fh.read()
                for m in re_trans.findall(content):
                    msgids.add(m.strip())
                for m in re_blocktrans.findall(content):
                    cleaned = ' '.join(m.split())
                    msgids.add(cleaned)
                for m in re_filter.findall(content):
                    msgids.add(m.strip())

# Master Comprehensive Translation Dictionary
AR_TRANSLATIONS = {
    "English": "الإنجليزية",
    "Arabic": "العربية",
    "Home": "الرئيسية",
    "Browse Projects": "تصفح المشاريع",
    "Categories": "الفئات",
    "Categories:": "الفئات:",
    "Category:": "الفئة:",
    "Category": "الفئة",
    "No categories yet": "لا توجد فئات بعد",
    "No categories": "لا توجد فئات",
    "No categories added yet.": "لم تتم إضافة أي فئات بعد.",
    "Search": "بحث",
    "Search:": "البحث:",
    "Search title or #tag...": "ابحث بالعنوان أو #الوسم...",
    "Search by title or #tag...": "ابحث بالعنوان أو #الوسم...",
    "Search campaigns by title or #tag...": "ابحث في المشاريع بالعنوان أو #الوسم...",
    "Search campaigns...": "ابحث في المشاريع...",
    "Create Campaign": "إنشاء مشروع",
    "Create Project": "إنشاء مشروع",
    "Admin Dashboard": "لوحة التحكم",
    "Dashboard": "لوحة التحكم",
    "Admin / Staff": "مشرف / طاقم العمل",
    "My Profile": "الملف الشخصي",
    "Profile": "الملف الشخصي",
    "My Projects": "مشاريعي",
    "My Donations": "تبرعاتي",
    "Django Admin": "لوحة إدارة دجانغو",
    "Logout": "تسجيل الخروج",
    "Login": "تسجيل الدخول",
    "Register": "إنشاء حساب",
    "Register here": "سجل من هنا",
    "Register & Send Verification Code": "تسجيل وإرسال رمز التحقق",
    "Register with a different email": "التسجيل ببريد إلكتروني آخر",
    "Register — Tamweel Crowd-Funding": "إنشاء حساب — تمويل للتمويل الجماعي",
    "Empowering Great Ideas in Egypt": "تمكين الأفكار العظيمة في مصر",
    "Empowering Ideas.": "تمكين الأفكار.",
    "Funding Egyptian Dreams.": "تمويل أحلام المصريين.",
    "Tamweel is the premier Egyptian crowdfunding platform connecting visionary project creators with passionate community backers.": "تمويل هي المنصة الرائدة في مصر للتمويل الجماعي، تربط أصحاب المشاريع المبتكرة بالداعمين من المجتمع.",
    "Egypt's premier crowd-funding platform to empower ideas and fund social good. Built for ITI Django Final Project.": "منصة التمويل الجماعي الأولى في مصر لتمكين الأفكار وتمويل المشاريع المجتمعية. مشروع تخرج مسار دجانغو بمعهد تكنولوجيا المعلومات ITI.",
    "Egypt's premier crowd-funding community. Discover, support, and raise funds for groundbreaking tech, creative culture, community development, and innovative ventures.": "مجتمع التمويل الجماعي الأول في مصر. اكتشف وادعم واجمع التمويل لمشاريع التكنولوجيا والثقافة وتنمية المجتمع والمشاريع المبتكرة.",
    "Platform": "المنصة",
    "TAMWEEL EGYPT PLATFORM": "منصة تمويل مصر",
    "All Projects": "جميع المشاريع",
    "Featured Campaigns": "المشاريع المميزة",
    "Featured Projects": "المشاريع المميزة",
    "Start a Campaign": "ابدأ مشروعاً",
    "Start a Project": "ابدأ مشروعاً",
    "Start a Fundraising Campaign": "بدء حملة تمويل جماعي",
    "Start a Campaign | CrowdFund Egypt": "بدء مشروع جديد | تمويل",
    "Top Rated": "الأعلى تقييماً",
    "Top Rated Campaigns": "المشاريع الأعلى تقييماً",
    "Top Rated Running Campaigns": "المشاريع القائمة الأعلى تقييماً",
    "Community Favorites": "المفضلة لدى المجتمع",
    "Fresh Campaigns": "مشاريع جديدة",
    "Latest Projects": "أحدث المشاريع",
    "Latest Campaigns": "أحدث المشاريع",
    "Latest": "الأحدث",
    "Oldest": "الأقدم",
    "User Account": "حساب المستخدم",
    "Create Account": "إنشاء حساب",
    "Create an Account": "إنشاء حساب جديد",
    "About & Support": "عن المنصة والدعم",
    "How It Works": "كيف تعمل المنصة",
    "Community Guidelines": "إرشادات المجتمع",
    "Privacy Policy": "سياسة الخصوصية",
    "Terms of Service": "شروط الخدمة",
    "Help & Support": "المساعدة والدعم",
    "All rights reserved.": "جميع الحقوق محفوظة.",
    "Made with": "صُنع بـ",
    "for Egyptian innovators.": "للمبتكرين في مصر.",
    "By": "بواسطة",
    "Goal:": "الهدف:",
    "Goal": "الهدف",
    "target": "الهدف",
    "Raised:": "تم جمع:",
    "Raised": "تم جمع",
    "raised of": "تم جمعها من إجمالي",
    "of": "من",
    "of the fundraising target.": "من المبلغ المستهدف للحملة.",
    "EGP": "جنيه",
    "EGP remaining": "جنيه متبقي",
    "Fund": "تمويل",
    "Featured": "مميز",
    "Standard": "عادي",
    "Running": "قائم",
    "Completed": "مكتمل",
    "Cancelled": "ملغى",
    "Campaign Closed": "الحملة مغلقة",
    "View Details": "عرض التفاصيل",
    "View All": "عرض الكل",
    "See All Projects": "عرض جميع المشاريع",
    "Fund Visionary Ideas Across Egypt": "موّل الأفكار المبتكرة في جميع أنحاء مصر",
    "Join Egypt's leading crowdfunding community. Support groundbreaking startups, creative endeavors, and impactful community initiatives today.": "انضم إلى مجتمع التمويل الجماعي الرائد في مصر. ادعم الشركات الناشئة المبتكرة والمبادرات المجتمعية المؤثرة اليوم.",
    "Join the Tamweel Crowdfunding Community": "انضم إلى مجتمع تمويل للتمويل الجماعي",
    "Explore Campaigns": "استكشف المشاريع",
    "Explore More Campaigns": "استكشف المزيد من المشاريع",
    "Explore Projects": "استكشف المشاريع",
    "Explore": "استكشف",
    "Explore Themes": "استكشف الموضوعات",
    "Start Fundraising": "ابدأ جمع التمويل",
    "Explore by Category": "استكشف حسب الفئات",
    "Browse by Category": "تصفح حسب الفئة",
    "Find inspiring projects tailored to causes and passions you care about.": "اعثر على مشاريع ملهمة تناسب اهتماماتك وقضاياك المفضلة.",
    "Find causes and projects that match your passion": "اعثر على القضايا والمشاريع التي تناسب شغفك",
    "Highest community ratings across all categories.": "أعلى تقييمات المجتمع عبر جميع الفئات.",
    "No top rated projects found.": "لا توجد مشاريع ذات تقييم عالي حالياً.",
    "Recently launched campaigns ready for your support.": "مشاريع أُطلقت حديثاً وجاهزة لدعمك.",
    "No latest projects found.": "لا توجد مشاريع حديثة حالياً.",
    "Why Choose Tamweel?": "لماذا تختار تمويل؟",
    "Verified Projects": "مشاريع موثقة",
    "Every campaign is reviewed and verified by our dedicated platform moderators for credibility and security.": "تتم مراجعة كل حملة والتحقق منها من قبل مشرفي المنصة لضمان المصداقية والأمان.",
    "Secure Local Payments": "دفع محلي آمن",
    "Support projects easily with Egyptian payment methods and multi-layer secure donation verification.": "ادعم المشاريع بسهولة عبر طرق الدفع المصرية ومع معايير أمان متعددة الطبقات.",
    "25% Cancellation Policy": "سياسة إلغاء 25%",
    "Cancellation Policy (25% Rule)": "سياسة الإلغاء (قاعدة 25%)",
    "Clear backer protection: creators can only cancel if total donations are strictly under 25% of target.": "حماية واضحة للداعمين: يمكن للمنشئ الإلغاء فقط إذا كانت التبرعات أقل من 25% من الهدف.",
    "Ready to Bring Your Idea to Life?": "جاهز لتحويل فكرتك إلى واقع؟",
    "Launch your fundraising campaign in minutes and connect with backers across Egypt.": "أطلق حملتك التمويلية في دقائق وتواصل مع داعمين في جميع أنحاء مصر.",
    "Create Your Campaign Today": "أنشئ مشروعك اليوم",
    "Discover Campaigns": "اكتشف المشاريع",
    "Discover, support, and track visionary projects across Egypt.": "اكتشف وادعم وتابع المشاريع المبتكرة في مصر.",
    "Showing active fundraising campaigns in Egypt": "عرض المشاريع التمويلية النشطة في مصر",
    "All Categories": "جميع الفئات",
    "All": "الكل",
    "Sort By": "ترتيب حسب",
    "Newest First": "الأحدث أولاً",
    "Most Funded": "الأكثر تمويلاً",
    "Highest Target": "أعلى هدف تمويلي",
    "Lowest Target": "أقل هدف تمويلي",
    "Target: High to Low": "الهدف: من الأعلى إلى الأقل",
    "Target: Low to High": "الهدف: من الأقل إلى الأعلى",
    "Filter": "تصفية",
    "Reset": "إعادة تعيين",
    "Reset Filters": "إعادة ضبط الفلاتر",
    "Showing": "عرض",
    "projects": "مشاريع",
    "Campaigns": "المشاريع",
    "No campaigns found": "لم يتم العثور على مشاريع",
    "No campaigns yet": "لا توجد مشاريع بعد",
    "No active campaigns yet. Be the first to start one!": "لا توجد مشاريع نشطة بعد. كن أول من يبدأ مشروعاً!",
    "Try adjusting your search criteria or category filters.": "جرّب تعديل معايير البحث أو تصفية الفئات.",
    "Try adjusting your search criteria or category filter.": "جرّب تعديل معايير البحث أو تصفية الفئات.",
    "Explore All Campaigns": "استكشف جميع المشاريع",
    "Back to all projects": "العودة إلى جميع المشاريع",
    "Explore campaigns in": "استكشف المشاريع في قسم",
    "No campaigns in this category yet": "لا توجد مشاريع في هذه الفئة بعد",
    "Be the first to launch an innovative project in this category!": "كن أول من يطلق مشروعاً مبتكراً في هذه الفئة!",
    "Launch Campaign": "أطلق مشروعاً",
    "My Campaigns": "مشاريعي",
    "Manage and track all the fundraising campaigns you've created.": "أدر وتابع جميع حملات التمويل التي أنشأتها.",
    "Manage and track your created fundraising projects": "أدر وتابع مشاريع التمويل التي أنشأتها",
    "New Campaign": "مشروع جديد",
    "Status": "الحالة",
    "Status:": "الحالة:",
    "Actions": "الإجراءات",
    "Edit": "تعديل",
    "Edit Project": "تعديل المشروع",
    "Edit Your Campaign": "تعديل مشروعك",
    "Cancel": "إلغاء",
    "You haven't created any campaigns yet": "لم تقم بإنشاء أي مشاريع بعد",
    "You haven't created any campaigns yet.": "لم تقم بإنشاء أي مشاريع بعد.",
    "You haven't launched any campaigns yet. Start one today!": "لم تطلق أي مشروع بعد. ابدأ واحداً اليوم!",
    "Launch your first fundraising campaign and start receiving community support today.": "أطلق أول حملة تمويلية لك وابدأ في تلقي دعم المجتمع اليوم.",
    "Create Your First Project": "أنشئ مشروعك الأول",
    "Create Your First Campaign": "أنشئ مشروعك الأول",
    "Track all your contributions and support for Egyptian innovators.": "تتبّع جميع مساهماتك ودعمك للمبتكرين في مصر.",
    "Track all your contributions and supported causes": "تتبّع جميع مساهماتك والقضايا التي دعمتها",
    "Campaign": "المشروع",
    "Amount": "المبلغ",
    "Donation Amount": "مبلغ التبرع",
    "Date": "التاريخ",
    "Deadline": "الموعد النهائي",
    "Action": "الإجراء",
    "View Project": "عرض المشروع",
    "You haven't backed any campaigns yet": "لم تدعم أي مشروع بعد",
    "You haven't made any donations yet": "لم تتبرع لأي مشروع بعد",
    "You haven't made any donations yet.": "لم تقم بأي تبرعات بعد.",
    "You haven't made any donations yet. Support an Egyptian dream today!": "لم تقم بأي تبرعات بعد. ادعم حلماً مصرياً اليوم!",
    "Explore Campaigns to Support": "استكشف المشاريع لدعمها",
    "No donations yet": "لا توجد تبرعات بعد",
    "Discover inspiring projects and make your first contribution today.": "اكتشف مشاريع ملهمة وقدّم مساهمتك الأولى اليوم.",
    "Cancel Campaign": "إلغاء المشروع",
    "Confirm Campaign Cancellation": "تأكيد إلغاء المشروع",
    "Are you sure you want to cancel this campaign?": "هل أنت متأكد من رغبتك في إلغاء هذا المشروع؟",
    "Are you sure you want to cancel this campaign? Once cancelled, the campaign will stop accepting further donations.": "هل أنت متأكد من رغبتك في إلغاء هذا المشروع؟ بمجرد الإلغاء، سيتوقف المشروع عن قبول أي تبرعات إضافية.",
    "No, Keep Campaign Running": "لا، استمر في تشغيل المشروع",
    "Platform Cancellation Policy:": "سياسة إلغاء المشاريع بالمنصة:",
    "According to Tamweel policy, a campaign can ONLY be cancelled if total donations received are strictly less than 25% of the total target amount.": "وفقاً لسياسة تمويل، يمكن إلغاء المشروع فقط إذا كان إجمالي التبرعات أقل تماماً من 25% من المبلغ المستهدف.",
    "In accordance with platform rules, a campaign can only be cancelled by its creator if total donations received are": "وفقاً لقواعد المنصة، يمكن للمنشئ إلغاء المشروع فقط إذا كان إجمالي التبرعات المستلمة",
    "less than 25%": "أقل من 25%",
    "Current donations:": "التبرعات الحالية:",
    "Current Total Donated:": "إجمالي التبرعات الحالية:",
    "Total target:": "الهدف الإجمالي:",
    "Total Target:": "إجمالي المبلغ المستهدف:",
    "Total Target (in EGP)": "إجمالي المبلغ المستهدف (بالجنيه)",
    "25% Threshold:": "حد الـ 25%:",
    "Allowed (Under 25%)": "مسموح (أقل من 25%)",
    "Not Allowed (25% or more)": "غير مسموح (25% أو أكثر)",
    "Once cancelled, this campaign will no longer accept donations and its status will permanently change to Cancelled.": "بمجرد الإلغاء، لن يقبل هذا المشروع تبرعات جديدة وستتغير حالته نهائياً إلى ملغى.",
    "Confirm Cancellation": "تأكيد الإلغاء",
    "Keep Campaign Active": "الإبقاء على المشروع قائماً",
    "Edit Campaign": "تعديل المشروع",
    "Start a New Campaign": "بدء مشروع جديد",
    "Update your campaign details and manage project images.": "حدّث تفاصيل مشروعك وأدر صور الحملة.",
    "Fill in the details below to launch your fundraising campaign on Tamweel.": "املأ التفاصيل أدناه لإطلاق حملتك التمويلية على تمويل.",
    "Share your vision with supporters across Egypt": "شارك رؤيتك وأفكارك مع الداعمين في جميع أنحاء مصر",
    "Campaign Title": "عنوان المشروع",
    "Enter a clear, descriptive title for your project": "أدخل عنواناً واضحاً ومعبراً عن مشروعك",
    "Short Tagline / Description": "نبذة موجزة / وصف مختصر",
    "A brief summary that appears on campaign cards": "ملخص موجز يظهر في بطاقات المشروع",
    "Full Campaign Details": "تفاصيل المشروع الكاملة",
    "Campaign Details & Story": "تفاصيل وقصة المشروع",
    "Tell backers everything about your project, goals, and execution plan": "أخبر الداعمين بكل شيء عن مشروعك وأهدافه وخطة التنفيذ",
    "Explain your goal, what the funds will be used for, and why people in Egypt should back you.": "اشرح هدفك، وفيما ستُستخدم الأموال، ولماذا ينبغي للناس في مصر دعم مشروعك.",
    "Fundraising Target (EGP)": "الهدف التمويلي (جنيه)",
    "Total amount needed to complete the project": "المبلغ الإجمالي المطلوب لإتمام المشروع",
    "Select the best fitting category": "اختر الفئة الأنسب للمشروع",
    "Campaign Timeline": "الجدول الزمني للحملة",
    "Start Date": "تاريخ البدء",
    "End Date": "تاريخ الانتهاء",
    "Start Date & Time": "تاريخ ووقت البدء",
    "End Date & Time": "تاريخ ووقت الانتهاء",
    "Tags": "الوسوم",
    "Tags:": "الوسوم:",
    "Tag:": "الوسم:",
    "Campaign Tags": "وسوم المشروع",
    "Popular Tags:": "الوسوم الشائعة:",
    "Enter tags separated by commas (e.g. tech, healthcare, cairo, education)": "أدخل الوسوم مفصولة بفواصل (مثال: تكنولوجيا، صحة، القاهرة، تعليم)",
    "Campaign Media & Images": "وسائط وصور المشروع",
    "Campaign Images": "صور المشروع",
    "Current Images": "الصور الحالية",
    "Primary Cover": "الغلاف الرئيسي",
    "Cover": "الغلاف",
    "No image": "لا توجد صورة",
    "Delete image": "حذف الصورة",
    "Remove image": "إزالة الصورة",
    "Remove Image": "حذف الصورة",
    "Remove Campaign Photo": "حذف صورة الحملة",
    "Upload New Images": "رفع صور جديدة",
    "Add Additional Photos": "إضافة صور إضافية",
    "Multiple Allowed": "مسموح صور متعددة",
    "Upload up to 5 project images (JPEG, PNG). First image will be used as the cover.": "ارفع حتى 5 صور للمشروع (JPEG, PNG). ستُستخدم الصورة الأولى كغلاف.",
    "Upload photos below to showcase your campaign in the gallery and project cards.": "ارفع الصور أدناه لعرض مشروعك في المعرض وبطاقات المشروع.",
    "Select one or more new photos to add to your campaign gallery.": "اختر صورة واحدة أو أكثر لإضافتها إلى معرض صور المشروع.",
    "You can select multiple photos. The first image will be used as the cover photo.": "يمكنك اختيار عدة صور. ستُستخدم الصورة الأولى كصورة الغلاف.",
    "No campaign images uploaded yet.": "لم يتم رفع أي صور للمشروع بعد.",
    "No additional photos uploaded for this campaign.": "لم يتم رفع صور إضافية لهذا المشروع.",
    "Individual Photo Management": "إدارة الصور الفردية",
    "Update Campaign": "تحديث المشروع",
    "Launch Campaign Now": "أطلق المشروع الآن",
    "Delete Project Image": "حذف صورة المشروع",
    "Are you sure you want to delete this image?": "هل أنت متأكد من رغبتك في حذف هذه الصورة؟",
    "Are you sure you want to remove this image?": "هل أنت متأكد من رغبتك في إزالة هذه الصورة؟",
    "Delete Image": "حذف الصورة",
    "This image will be permanently removed from your campaign gallery and storage. Other campaign images and project details remain unaffected.": "ستتم إزالة هذه الصورة نهائياً من معرض المشروع ومساحة التخزين. لن تتأثر باقي صور وتفاصيل المشروع.",
    "Creator": "المنشئ",
    "Campaign Organizer": "منظم الحملة",
    "Organizer:": "المنظم:",
    "Ends": "ينتهي في",
    "Community Rating": "تقييم المجتمع",
    "Project Rating": "تقييم المشروع",
    "reviews": "مراجعات",
    "ratings": "تقييمات",
    "Target & Progress": "الهدف والتقدم",
    "Target": "الهدف",
    "Backers": "الداعمين",
    "Supporters": "الداعمين",
    "funded": "مموّل",
    "Back This Project": "ادعم هذا المشروع",
    "Donation Amount (EGP)": "مبلغ التبرع (جنيه)",
    "Select Amount:": "اختر المبلغ:",
    "Minimum 10 EGP": "الحد الأدنى 10 جنيه",
    "Donate Now": "تبرع الآن",
    "100% of your donation reaches the campaign.": "100% من تبرعك يصل إلى المشروع مباشرة.",
    "This campaign is no longer accepting donations.": "هذا المشروع لا يقبل تبرعات إضافية حالياً.",
    "Please log in to donate to this project.": "يرجى تسجيل الدخول للتبرع لهذا المشروع.",
    "Log In to Donate": "سجل الدخول للتبرع",
    "Log in to Donate": "سجل الدخول للتبرع",
    "Log in to support this cause": "سجل الدخول لدعم هذه القضية",
    "Rate this Project": "قيّم هذا المشروع",
    "Rate this campaign": "قيّم هذه الحملة",
    "Rate this campaign:": "قيّم هذا المشروع:",
    "Your Rating:": "تقييمك:",
    "Your rating:": "تقييمك:",
    "Rate": "تقييم",
    "Rate Project": "تقييم المشروع",
    "Log in to Rate": "سجل الدخول للتقييم",
    "Remove Rating": "حذف التقييم",
    "Remove your rating": "حذف تقييمك",
    "Remove your rating?": "هل تريد حذف تقييمك؟",
    "Your rating will be removed and the project's average rating will be recalculated.": "سيتم حذف تقييمك وإعادة حساب متوسط تقييم المشروع.",
    "Report this campaign": "إبلاغ عن هذا المشروع",
    "Report Project": "الإبلاغ عن المشروع",
    "Report Campaign": "الإبلاغ عن المشروع",
    "Report Inappropriate Content": "الإبلاغ عن محتوى غير لائق",
    "Please describe why you are reporting this campaign:": "يرجى توضيح سبب الإبلاغ عن هذا المشروع:",
    "Please describe the inappropriate content or policy violation regarding this campaign:": "يرجى وصف المحتوى غير اللائق أو مخالفة الشروط المتعلقة بهذا المشروع:",
    "Campaign Description": "وصف المشروع",
    "About this Campaign": "عن هذا المشروع",
    "About the Creator": "عن منشئ المشروع",
    "Member since": "عضو منذ",
    "Cairo, Egypt": "القاهرة، مصر",
    "Location & Trust": "الموقع والموثوقية",
    "Verified": "موثق",
    "Community Comments": "تعليقات المجتمع",
    "Comments": "التعليقات",
    "Post a Comment": "أضف تعليقاً",
    "Write a constructive comment or question...": "اكتب تعليقاً بنّاءً أو سؤالاً...",
    "Post Comment": "نشر التعليق",
    "Log in to join the conversation and leave a comment.": "سجل الدخول للمشاركة في المحادثة وترك تعليق.",
    "to leave a comment or ask a question.": "لكتابة تعليق أو طرح سؤال.",
    "Reply": "رد",
    "Report": "إبلاغ",
    "Delete": "حذف",
    "Write a reply...": "اكتب رداً...",
    "Send Reply": "إرسال الرد",
    "Post Reply": "نشر الرد",
    "Report Reply": "الإبلاغ عن الرد",
    "Delete Reply": "حذف الرد",
    "Delete this reply?": "هل تريد حذف هذا الرد؟",
    "Report Comment": "الإبلاغ عن التعليق",
    "Please describe why you are reporting this comment:": "يرجى توضيح سبب الإبلاغ عن هذا التعليق:",
    "Why are you reporting this comment?": "لماذا تبلغ عن هذا التعليق؟",
    "Why are you reporting this reply?": "لماذا تبلغ عن هذا الرد؟",
    "Explain the violation...": "اشرح المخالفة بالتفصيل...",
    "Delete Comment": "حذف التعليق",
    "Are you sure you want to delete this comment? This action cannot be undone.": "هل أنت متأكد من رغبتك في حذف هذا التعليق؟ لا يمكن التراجع عن هذا الإجراء.",
    "This action cannot be undone and will permanently remove this comment": "لا يمكن التراجع عن هذا الإجراء وسيتم حذف التعليق نهائياً",
    "and its replies": "وجميع الردود التابعة له",
    "This action cannot be undone and will permanently remove your reply.": "لا يمكن التراجع عن هذا الإجراء وسيتم حذف ردك نهائياً.",
    "Confirmation for": "تأكيد لـ",
    "No comments yet. Be the first to start the discussion!": "لا توجد تعليقات بعد. كن أول من يبدأ النقاش!",
    "No comments yet. Start the conversation!": "لا توجد تعليقات بعد. ابدأ المحادثة الآن!",
    "Similar Campaigns": "مشاريع مشابهة",
    "Similar Projects": "مشاريع مشابهة",
    "Recommended for you": "موصى بها لك",
    "Staff Picks": "اختيارات فريق العمل",
    "Support Social Good": "ادعم الخير والمجتمع",
    "Tamweel Backer Guarantee": "ضمان تمويل للداعمين",
    "Tamweel Guarantee": "ضمان تمويل",
    "Your contribution is protected under our 25% refund threshold policy. Verified Egyptian projects only.": "مساهمتك محمية بموجب سياسة استرداد 25%. مشاريع مصرية موثقة فقط.",
    "Verified Egyptian phone numbers & safe crowdfunding protocols.": "أرقام هواتف مصرية موثقة وبروتوكولات تمويل جماعي آمنة.",
    "Secure local Egyptian payment methods.": "طرق دفع محلية مصرية آمنة.",
    "Real-time transparent funding updates.": "تحديثات تمويلية شفافة في الوقت الفعلي.",
    "Hidden Fees": "رسوم خفية",
    "Support verified Egyptian innovations directly.": "ادعم الابتكارات المصرية الموثقة مباشرة.",
    "Every donation directly powers students, innovators, doctors, and artisans across all Egyptian governorates.": "كل تبرع يدعم مباشرة الطلاب والمبتكرين والأطباء والحرفيين في جميع المحافظات المصرية.",
    "Welcome Back": "مرحباً بعودتك",
    "Log into your Tamweel account": "سجل الدخول إلى حسابك في تمويل",
    "Log in to Tamweel Crowdfunding": "تسجيل الدخول إلى تمويل للتمويل الجماعي",
    "Email Address": "البريد الإلكتروني",
    "Enter your registered email": "أدخل بريدك الإلكتروني المسجل",
    "We will send a 6-digit OTP verification code to this email.": "سنرسل رمز تحقق OTP مكوناً من 6 أرقام إلى هذا البريد الإلكتروني.",
    "Password": "كلمة المرور",
    "Enter your password": "أدخل كلمة المرور",
    "Remember me": "تذكرني",
    "Forgot password?": "نسيت كلمة المرور؟",
    "Forgot Password?": "نسيت كلمة المرور؟",
    "or": "أو",
    "OR": "أو",
    "Continue with Facebook": "المتابعة باستخدام فيسبوك",
    "Don't have an account?": "ليس لديك حساب؟",
    "Create one now": "أنشئ حساباً الآن",
    "Join Tamweel": "انضم إلى تمويل",
    "Create your account to start fundraising or backing projects": "أنشئ حسابك لبدء جمع التمويل أو دعم المشاريع",
    "First Name": "الاسم الأول",
    "Last Name": "اسم العائلة",
    "Mobile Phone (Egyptian)": "رقم الهاتف المحمول (مصري)",
    "Must be a valid Egyptian mobile number (e.g. 01012345678, 011..., 012..., 015...).": "يجب إدخال رقم محمول مصري صحيح (مثال: 01012345678، 011...، 012...، 015...).",
    "Confirm Password": "تأكيد كلمة المرور",
    "Profile Picture": "الصورة الشخصية",
    "Profile Picture (Optional)": "الصورة الشخصية (اختياري)",
    "Already have an account?": "لديك حساب بالفعل؟",
    "Log in here": "سجل الدخول من هنا",
    "Verify Your Account": "تأكيد حسابك",
    "Verify Your Email — Tamweel": "تأكيد بريدك الإلكتروني — تمويل",
    "Enter the 6-digit verification code sent to your email": "أدخل رمز التحقق المكون من 6 أرقام المرسل إلى بريدك الإلكتروني",
    "We sent a 6-digit verification code and an activation link to": "أرسلنا رمز تحقق مكوناً من 6 أرقام ورابط تفعيل إلى",
    "You can enter your 6-digit code below or click the activation link in your email to verify directly.": "يمكنك إدخال الرمز المكون من 6 أرقام أدناه أو الضغط على رابط التفعيل في بريدك الإلكتروني للتأكيد مباشرة.",
    "Verification Code (OTP)": "رمز التحقق (OTP)",
    "Verify Account": "تأكيد الحساب",
    "Verify Code": "تأكيد الرمز",
    "Resend Code": "إعادة إرسال الرمز",
    "seconds": "ثانية",
    "Didn't receive the email?": "لم يصلك البريد الإلكتروني؟",
    "Didn't receive the verification code?": "لم يصلك رمز التحقق؟",
    "Email Delivery Issue": "مشكلة في إرسال البريد",
    "Verification Code Sent": "تم إرسال رمز التحقق",
    "Email Sending Issue": "مشكلة في تسليم البريد",
    "Your account was registered, but we encountered an issue sending the verification code to": "تم تسجيل حسابك ولكن واجهتنا مشكلة أثناء إرسال رمز التحقق إلى",
    "Note:": "ملاحظة:",
    "Please check your email address or check server configuration.": "يرجى التحقق من صحة بريدك الإلكتروني أو مراجعة إعدادات الخادم.",
    "Try Again": "حاول مجدداً",
    "Go to OTP Verification": "الانتقال إلى إدخال رمز التحقق",
    "Verify Your Email": "تحقق من بريدك الإلكتروني",
    "We sent a 6-digit verification code to": "أرسلنا رمز تحقق مكوناً من 6 أرقام إلى",
    "Notice:": "تنبيه:",
    "Your verification code expires in 10 minutes.": "تنتهي صلاحية رمز التحقق خلال 10 دقائق.",
    "Enter Verification Code": "أدخل رمز التحقق",
    "Account Activated | CrowdFund Egypt": "تم تفعيل الحساب | تمويل",
    "Account Activated Successfully!": "تم تفعيل الحساب بنجاح!",
    "Welcome aboard,": "أهلاً بك معنا،",
    "Your email has been verified and your account is active.": "تم تأكيد بريدك الإلكتروني وحسابك الآن مفعّل بالكامل.",
    "Log In Now": "سجل الدخول الآن",
    "Activation Notice": "إشعار التفعيل",
    "This activation link is invalid, expired, or has already been used.": "رابط التفعيل هذا غير صالح، منتهي الصلاحية، أو تم استخدامه مسبقاً.",
    "Resend Verification Email": "إعادة إرسال بريد التفعيل",
    "Go to Login": "الذهاب لتسجيل الدخول",
    "Reset Password": "إعادة تعيين كلمة المرور",
    "Forgot your password?": "هل نسيت كلمة المرور؟",
    "Enter your email to receive a password reset link": "أدخل بريدك الإلكتروني لاستلام رابط إعادة تعيين كلمة المرور",
    "Enter your email address:": "أدخل عنوان بريدك الإلكتروني:",
    "Send Reset Link": "إرسال رابط التعيين",
    "Back to Login": "العودة لتسجيل الدخول",
    "Password Reset Email Sent | Tamweel": "تم إرسال بريد تعيين كلمة المرور | تمويل",
    "Password Reset Sent": "تم إرسال رابط التعيين",
    "We've emailed you instructions for setting your password. If an account exists with the email you entered, you should receive them shortly.": "أرسلنا تعليمات تعيين كلمة المرور إلى بريدك الإلكتروني. إذا كان الحساب موجوداً، فستصلك الرسالة قريباً.",
    "Return to Login": "العودة لتسجيل الدخول",
    "Create a new secure password for your account": "أنشئ كلمة مرور جديدة وآمنة لحسابك",
    "New Password": "كلمة المرور الجديدة",
    "The password reset link was invalid or has already expired. Please request a new password reset.": "رابط إعادة تعيين كلمة المرور غير صالح أو منتهي الصلاحية. يرجى طلب رابط جديد.",
    "Request New Link": "طلب رابط جديد",
    "Password Reset Complete | Tamweel": "اكتمل تعيين كلمة المرور | تمويل",
    "Password Successfully Reset!": "تمت إعادة تعيين كلمة المرور بنجاح!",
    "Your password has been changed. You can now log into your account with your new password.": "تم تغيير كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول باستخدام كلمة المرور الجديدة.",
    "Log In": "تسجيل الدخول",
    "Delete Account | CrowdFund Egypt": "حذف الحساب | تمويل",
    "Delete Your Account": "حذف حسابك",
    "Permanent Account Deletion": "حذف نهائي للحساب",
    "Warning: This action cannot be undone!": "تحذير: لا يمكن التراجع عن هذا الإجراء!",
    "Deleting your account will permanently delete your personal information, profile, campaigns, and donation records.": "سيؤدي حذف حسابك إلى مسح بياناتك الشخصية وملفك ومشاريعك وسجلات تبرعاتك بشكل نهائي.",
    "Please enter your password to confirm:": "يرجى إدخال كلمة المرور لتأكيد الحذف:",
    "No, Keep My Account": "لا، احتفظ بحسابي",
    "Permanently Delete": "حذف نهائي",
    "My Profile | CrowdFund Egypt": "ملفي الشخصي | تمويل",
    "Remove Photo": "حذف الصورة",
    "Mobile:": "الهاتف:",
    "Country:": "الدولة:",
    "Egypt": "مصر",
    "Birthdate:": "تاريخ الميلاد:",
    "Facebook:": "فيسبوك:",
    "Profile Link": "رابط الملف",
    "Edit Profile": "تعديل الملف الشخصي",
    "Delete Account": "حذف الحساب",
    "Campaigns Created By You": "المشاريع التي أنشأتها",
    "Your Contributions": "مساهماتك وتبرعاتك",
    "Remove Profile Photo": "حذف الصورة الشخصية",
    "Remove your profile photo?": "هل تريد حذف صورتك الشخصية؟",
    "Your profile photo will be removed and your default avatar will be shown instead.": "ستتم إزالة صورتك الشخصية والاعتماد على الصورة الافتراضية بدلاً منها.",
    "Edit Profile | CrowdFund Egypt": "تعديل الملف الشخصي | تمويل",
    "Email address cannot be changed.": "لا يمكن تعديل عنوان البريد الإلكتروني.",
    "Current Profile Picture": "الصورة الشخصية الحالية",
    "Uploaded avatar": "الصورة الرمزية المرفوعة",
    "Change Photo": "تغيير الصورة",
    "Upload New Photo": "رفع صورة جديدة",
    "Birthdate": "تاريخ الميلاد",
    "Country": "الدولة",
    "Facebook Profile URL": "رابط حساب فيسبوك",
    "Save Changes": "حفظ التغييرات",
    "Admin Dashboard – Tamweel Crowd-Funding": "لوحة تحكم الإدارة – تمويل للتمويل الجماعي",
    "Staff Only": "خاص بالإدارة",
    "Welcome back,": "مرحباً بعودتك،",
    "Manage projects, users, moderation reports, and platform settings.": "إدارة المشاريع والمستخدمين وبلاغات الإشراف وإعدادات المنصة.",
    "New Project": "مشروع جديد",
    "View Site": "زيارة الموقع",
    "Total Users": "إجمالي المستخدمين",
    "Registered accounts": "حسابات مسجلة",
    "Projects": "المشاريع",
    "Total campaigns": "إجمالي المشاريع",
    "Active": "النشطة",
    "Running campaigns": "مشاريع قائمة",
    "Donations": "التبرعات",
    "Transactions": "عمليات تبرع",
    "Total Raised": "إجمالي المبالغ",
    "Across platform": "عبر المنصة",
    "Reports": "البلاغات",
    "Need review": "تتطلب المراجعة",
    "Users": "المستخدمين",
    "Platform Campaigns": "مشاريع المنصة",
    "Project": "المشروع",
    "Target & Raised": "الهدف والمجموع",
    "Rating": "التقييم",
    "Click to unmark as featured": "انقر لإلغاء التمييز",
    "Click to mark as featured": "انقر لتمييز المشروع",
    "View": "عرض",
    "Delete Project": "حذف المشروع",
    "Are you sure you want to delete this project?": "هل أنت متأكد من رغبتك في حذف هذا المشروع؟",
    "No projects in database yet.": "لا توجد مشاريع في قاعدة البيانات بعد.",
    "User Management": "إدارة المستخدمين",
    "Manage registered user accounts, verification statuses, and account removals.": "إدارة حسابات المستخدمين المسجلين وحالات التوثيق والحذف.",
    "Total Registered:": "إجمالي المسجلين:",
    "Search users by name, email, or phone...": "ابحث بالاسم أو البريد أو الهاتف...",
    "Clear": "مسح",
    "Showing results for": "عرض نتائج البحث عن",
    "found": "تم العثور عليها",
    "User": "المستخدم",
    "Mobile Phone": "رقم الهاتف",
    "Verification Status": "حالة التوثيق",
    "Role": "الدور",
    "Joined Date": "تاريخ الانضمام",
    "Active / Verified": "نشط / موثق",
    "Unverified / Inactive": "غير موثق / غير نشط",
    "Super Admin": "مشرف عام",
    "Staff": "طاقم العمل",
    "Make Admin": "تعيين كمشرف",
    "Remove Admin": "إلغاء صفة المشرف",
    "Deactivate": "تعطيل",
    "Activate": "تفعيل",
    "Delete User": "حذف المستخدم",
    "Current Account": "الحساب الحالي",
    "No users found matching your search.": "لم يتم العثور على مستخدمين يطابقون بحثك.",
    "Clear Search Filter": "مسح تصفية البحث",
    "Reported Projects": "المشاريع المُبلّغ عنها",
    "Reported By": "أُبلغ بواسطة",
    "Reason": "السبب",
    "Pending": "قيد المراجعة",
    "Resolved": "تمت المعالجة",
    "Mark Resolved": "تحديد كتمت المعالجة",
    "Resolve": "معالجة",
    "Dismiss Report": "رفض البلاغ",
    "Dismiss": "رفض",
    "Reviewed": "تمت المراجعة",
    "No reported projects.": "لا توجد بلاغات على المشاريع.",
    "Reported Comments": "التعليقات المُبلّغ عنها",
    "Comment Content": "محتوى التعليق",
    "Comment deleted": "تم حذف التعليق",
    "Delete Offensive Comment": "حذف التعليق المخالف",
    "Delete this comment?": "حذف هذا التعليق؟",
    "No reported comments.": "لا توجد بلاغات على تعليقات.",
    "Platform Categories": "فئات المنصة",
    "Category Name": "اسم الفئة",
    "Slug": "المعرف اللطيف",
    "campaigns": "مشاريع",
    "Delete category": "حذف الفئة",
    "Delete Category": "حذف الفئة",
    "Contains projects": "تحتوي على مشاريع",
    "Protected": "محمية",
    "Add New Category": "إضافة فئة جديدة",
    "Description (Optional)": "الوصف (اختياري)",
    "Brief description of this category...": "وصف موجز لهذه الفئة...",
    "Create Category": "إنشاء الفئة",
    "Delete User Account": "حذف حساب المستخدم",
    "Delete this user?": "حذف هذا المستخدم؟",
    "Are you sure you want to permanently delete": "هل أنت متأكد من رغبتك في الحذف النهائي للمستخدم",
    "and all associated data from the platform?": "وجميع البيانات المرتبطة به من المنصة؟",
    "Permanent Action:": "إجراء دائم:",
    "This will delete all account data and cannot be undone.": "سيؤدي هذا إلى حذف جميع بيانات الحساب ولا يمكن التراجع عنه.",
    "Promote to Administrator": "ترقية إلى مسؤول",
    "Make this user an administrator?": "منح صلاحيات المسؤول لهذا المستخدم؟",
    "This will grant": "سيمنح هذا الإجراء",
    "staff privileges to access the Admin Dashboard, view reports, and moderate content.": "صلاحيات طاقم العمل للوصول إلى لوحة التحكم ومراجعة البلاغات والإشراف.",
    "Remove Administrator Access": "إلغاء صلاحيات المسؤول",
    "Remove administrator access?": "إلغاء صلاحيات المسؤول؟",
    "Remove administrator privileges from": "إلغاء صلاحيات المسؤول من",
    "They will return to standard user permissions. Their account, projects, and donations will remain intact.": "سيعود إلى صلاحيات المستخدم العادي، وستظل حساباته ومشاريعه وتبرعاته محفوظة.",
    "Open Tamweel Assistant": "فتح مساعد تمويل الذكي",
    "Tamweel AI Assistant": "مساعد تمويل الذكي",
    "Tamweel Assistant": "مساعد تمويل",
    "Online • AI Support": "متصل • دعم بالذكاء الاصطناعي",
    "Close Tamweel Assistant": "إغلاق مساعد تمويل",
    "Hi! I'm the <strong>Tamweel Assistant</strong>. How can I help you today?": "مرحباً! أنا <strong>مساعد تمويل</strong>. كيف يمكنني مساعدتك اليوم؟",
    "Quick questions:": "أسئلة سريعة:",
    "How do I create a campaign?": "كيف أنشئ مشروعاً؟",
    "How do I donate?": "كيف أتبرع؟",
    "How do I reset my password?": "كيف أعيد تعيين كلمة المرور؟",
    "Ask Tamweel anything...": "اسأل تمويل عن أي شيء...",
    "Your message to Tamweel Assistant": "رسالتك إلى مساعد تمويل",
    "Send message": "إرسال الرسالة",
    "Explore Campaigns | CrowdFund Egypt": "استكشف المشاريع | تمويل",
    "TAMWEEL – Crowd-Funding Egypt | Fund Egyptian Innovation": "تمويل – منصة التمويل الجماعي الأولى في مصر | موّل الابتكار المصري",
    "TAMWEEL — Crowd-Funding Egypt | Fund Egyptian Innovation": "تمويل — منصة التمويل الجماعي الأولى في مصر | موّل الابتكار المصري",
    "Register – Tamweel Crowd-Funding": "إنشاء حساب – تمويل للتمويل الجماعي",
    "Register — Tamweel Crowd-Funding": "إنشاء حساب — تمويل للتمويل الجماعي",
    "Verify Your Email – Tamweel": "تأكيد بريدك الإلكتروني – تمويل",
    "Verify Your Email — Tamweel": "تأكيد بريدك الإلكتروني — تمويل",
    "ago": "مضت",
    "Previous": "السابق",
    "Next": "التالي",
    "Submit Report": "إرسال البلاغ"
}

# Add extracted msgids to dictionary if not present
missing_count = 0
for mid in msgids:
    if mid not in AR_TRANSLATIONS:
        AR_TRANSLATIONS[mid] = mid
        print(f"WARNING: Missing custom translation for: {mid}")
        missing_count += 1

if missing_count == 0:
    print("ALL extracted template strings are 100% translated!")

# Build PO file
po_path = os.path.join('locale', 'ar', 'LC_MESSAGES', 'django.po')
os.makedirs(os.path.dirname(po_path), exist_ok=True)

with open(po_path, 'w', encoding='utf-8') as f:
    f.write('''# Tamweel Arabic Translations
# Complete Website Translation (Arabic / English)
msgid ""
msgstr ""
"Project-Id-Version: Tamweel 1.0\\n"
"Report-Msgid-Bugs-To: \\n"
"POT-Creation-Date: 2026-08-30 17:00+0300\\n"
"PO-Revision-Date: 2026-08-30 17:00+0300\\n"
"Last-Translator: Tamweel Team\\n"
"Language-Team: Arabic\\n"
"Language: ar\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;\\n"

''')

    for mid, mstr in sorted(AR_TRANSLATIONS.items()):
        esc_id = mid.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n"\n"')
        esc_str = mstr.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n"\n"')
        f.write(f'msgid "{esc_id}"\n')
        f.write(f'msgstr "{esc_str}"\n\n')

print(f"Written {len(AR_TRANSLATIONS)} entries to {po_path}")

# Compile to MO file
mo_path = os.path.join('locale', 'ar', 'LC_MESSAGES', 'django.mo')
cat = compile_po.po_to_dict(po_path)
compile_po.dict_to_mo(cat, mo_path)
print(f"Compiled {len(cat)} binary translations to {mo_path}")
