# Generated by Django 6.1 on 2026-08-26 06:32

import accounts.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='last_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, default='', help_text='Egyptian phone number (e.g., 01012345678 or +201012345678)', max_length=20, validators=[accounts.validators.validate_egyptian_phone], verbose_name='Mobile Phone'),
        ),
        migrations.CreateModel(
            name='FacebookSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(max_length=100, unique=True, verbose_name='Facebook User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facebook Social Account',
                'verbose_name_plural': 'Facebook Social Accounts',
            },
        ),
    ]
